apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mahendar-deployment
  namespace: mahendar
spec:
  selector:
    matchLabels:
      app: mahendar
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mahendar
    spec:
      containers:
      - name: mahendar
        image: 349948765351.dkr.ecr.ap-south-1.amazonaws.com/mahendar:latest
        ports:
                - containerPort: 80:

